#!/bin/sh

ARGS=$(cat -- <<-ARGS
	# Use floating point division by default
	from __future__ import division
	
	# Import common math functions into default namespace
	from math import *
	
	# Define some common constants
	c=299792458
	g=9.82
	
	ARGS
)

if [ ${#} -eq 0 ]; then
	python -ic "${ARGS}"
else
	python -c "${ARGS}; print ${*};"
fi
