#!/bin/sh
usage() {
	cat <<-USAGE
	A Python shell with math functions and physical constants in the namespace.

	usage: ${0##*/} [-h] [EXPR]

	optional arguments:
	  EXPR  expression to be evaluated
	  -h    this text

	Without arguments the python interpreter is started.
	USAGE
	exit 1
}

while getopts "h" option; do
	case $option in
		h|\? )	usage;;
	esac
done
shift $((OPTIND-1))

ARGS='
# Use floating point division by default.
from __future__ import division

# Import common math functions into default namespace.
from math import *

# Enable tab completion of variables and functions.
import readline
import rlcompleter

readline.parse_and_bind("tab: complete")

# Define some common constants.
c  = 299792458           # Speed of light in a vacuum  [m/s]
g  = 9.82                # Gravitational acceleration  [m/s²]
e0 = 8.854187817620e-12  # Vacuum permittivity, ε_0    [F/m]
m0 = pi*4e-7             # Vacuum permeability, μ_0    [Vs/Am]
Z0 = sqrt(m0/e0)         # Vacuum impedance, Z_0       [Ω]

# Alias log() (the natural logarithm) to ln().
ln = log

# Compute best fractional approximation.
def frac(num, limit=10**6):
    from fractions import Fraction
    return Fraction(num).limit_denominator(limit)

# 2-norm function for vectors. Note that it handles both an adaptive number of
# direct arguments and list/tuple input.
def norm(*args):
    import numpy.linalg as npl
    return npl.norm(args)

#' # Do not end with a newline.

if [ ${#} -eq 0 ]; then
	python -ic "${ARGS}"
else
	python -c "${ARGS}; print ${*};"
fi
